name: Main workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Application a.k.a. image version"
        required: false

env:
  IMAGE_NAME: hello-world

permissions:
    id-token: 'write'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login with service principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Build image
        run: docker build --no-cache -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }} --build-args VERSION=${{ github.event.inputs.version }} .
      - name: Login to container registry
        uses: azure/cli@v1
        with:
          inlineScript: az acr login -n ${{ secrets.AZURE_REGISTRY_NAME }}
      - name: Push image to container registry
        run: docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}